version: '3'
services:
  postgres:
    image: postgres:15
    container_name: crm_postgres
    restart: always
    environment:
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpassword
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
